version: "3.3"

services:
  app:
    container_name: api-rest
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 3333
    ports:
      - "3333:3333"
